package com.verizon.oneparser.common

import org.apache.spark.sql.SparkSession

object HiveTableStructure {

  val qcommTableStruct:String = "(dmtimestamp             timestamp," +
    "index                   int," +
    "logcode                 string," +
    "hexlogcode              string," +
    "version                 int," +
    "filteredrsrp            array<double>," +
    "numberofneighborcells   int," +
    "servingfilteredrsrp     double," +
    "dlgrantccid             array<array<array<int>>>," +
    "carrierindex0xb14d      string," +
    "carrierindex0xb14e      string," +
    "carrierindex0xb126      string," +
    "carrierindex            string," +
    "cqicw0                  int," +
    "cqicw1                  int," +
    "cqicw00xb14e            int," +
    "cqicw1show0xb14e        int," +
    "cqicw10xb14e            int," +
    "csftxmode               string," +
    "pucchreporttype         string," +
    "puschreportmode         string," +
    "rankindexstr            string," +
    "rankindexstr0xb14e      string," +
    "rankindexint            int," +
    "startsystemframenumber  int," +
    "startsystemsubframenumber       int," +
    "puschtxpower            array<int>," +
    "frequency               int," +
    "physicalcellid          int," +
    "numrecords0xb139        int," +
    "numrecords0xb172        int," +
    "numrecords0xb173        int," +
    "numrecords0xb16e        int," +
    "numrecords0xb16f        int," +
    "numrecords0xb18a        int," +
    "framenum                array<int>," +
    "subframenum             array<int>," +
    "crcresult               array<string>," +
    "discardedretxpresent    array<array<string>>," +
    "harqid                  array<array<int>>," +
    "ndi                     array<array<int>>," +
    "rv                      array<array<int>>," +
    "tb_index                array<array<int>>," +
    "tb_size0xb139           array<int>," +
    "tb_size0xb173           array<int>," +
    "numprb0xb173            array<int>," +
    "numlayers               array<int>," +
    "numtransportblockspresent       array<int>," +
    "servingcellindex        array<string>," +
    "numofstreams            array<bigint>," +
    "retransmissionnumber    array<array<string>>," +
    "transportblockcrc       array<array<string>>," +
    "format                  array<string>," +
    "rachproceduremode       string," +
    "rnti_type               string," +
    "rnti_value              int," +
    "pdcch_timing_sfn        array<int>," +
    "pdcch_timing_subsfn     array<int>," +
    "phich_value1            array<array<string>>," +
    "phich_value             array<array<string>>," +
    "modulationtype          array<string>," +
    "dlgrantpresent          array<string>," +
    "dlgrantformat           array<array<string>>," +
    "hopingflag              array<array<string>>," +
    "totaltxpower            array<array<bigint>>," +
    "chaintype               array<string>," +
    "fi                      array<int>," +
    "gi                      array<int>," +
    "pucch_tx_power0xb16e    array<int>," +
    "pucch_tx_power0xb16f    array<int>," +
    "insynccount             array<int>," +
    "outsyncbler             array<double>," +
    "outsynccount            array<int>," +
    "t310_timer_status       array<int>," +
    "cdrxevent               array<string>," +
    "currentsfnsf            array<int>," +
    "retxindex               array<string>," +
    "prb                     array<int>," +
    "modul                   array<string>," +
    "ulbandwidth             string," +
    "dlbandwidth             string," +
    "ltecellid               int," +
    "wcdmacellid             int," +
    "gsmcellid               int," +
    "allowedaccess           string," +
    "freqbandindicator       int," +
    "ulfreq                  int," +
    "dlfreq                  int," +
    "mcc                     int," +
    "mnc                     int," +
    "trackingareacode        int," +
    "modstream0              array<string>," +
    "modstream1              array<string>," +
    "pdschrntilid            int," +
    "pdschrntitype           array<string>," +
    "servingcellid           int," +
    "transmissionscheme      array<string>," +
    "freqselpmi              array<string>," +
    "spatialrank             array<string>," +
    "powerheadroom           array<bigint>," +
    "srstxpower              array<int>," +
    "pmiindex                int," +
    "ulcarrierindex          array<string>," +
    "bandclass               int," +
    "channel0x1017           int," +
    "channel0x119a           int," +
    "pilotpn                 int," +
    "pilotpnaslist           array<int>," +
    "rxpower                 array<double>," +
    "txpower                 int," +
    "cdmatxstatus            string," +
    "hrpdstate               string," +
    "pdnrat                  string," +
    "lacid                   int," +
    "psc                     int," +
    "racid                   int," +
    "l2state                 string," +
    "rrstate                 string," +
    "rxlev                   int," +
    "bsicbcc                 int," +
    "bsicncc                 int," +
    "numtxantennas           array<string>," +
    "numrxantennas           array<string>," +
    "timingadvance           int," +
    "timingadvanceincl       string," +
    "dlpathloss0xb16e        array<int>," +
    "dlpathloss0xb16f        array<int>," +
    "lai                     array<tinyint>," +
    "bccharfcn               int," +
    "latitude                string," +
    "longitude               string," +
    "latitude2               string," +
    "longitude2              string," +
    "country                 string," +
    "county                  string," +
    "region                  string," +
    "statecode               string," +
    "evdorxpwr               array<double>," +
    "evdotxpwr               array<double>," +
    "vvqjitter               string," +
    "vvq                     string," +
    "rtploss                 string," +
    "cdmarftxpower           float," +
    "txgainadj               int," +
    "hasgps                  int," +
    "exceptionoccured        boolean," +
    "exceptioncause          string," +
    "scc1cqicw0              int," +
    "scc2cqicw0              int," +
    "scc3cqicw0              int," +
    "scc4cqicw0              int," +
    "scc5cqicw0              int," +
    "scc1cqicw1              int," +
    "scc2cqicw1              int," +
    "scc3cqicw1              int," +
    "scc4cqicw1              int," +
    "scc5cqicw1              int," +
    "pccrankindex            int," +
    "scc1rankindex            int," +
    "scc2rankindex            int," +
    "scc3rankindex            int," +
    "scc4rankindex            int," +
    "scc5rankindex            int," +
    "missingversion           int," +
    "firstFN_0xB173           int," +
    "lastFN_0xB173           int," +
    "firstSFN_0xB173           int," +
    "lastSFN_0xB173           int," +
    "pcellTBSize_0xB173           int," +
    "scc1TBSize_0xB173           int," +
    "scc2TBSize_0xB173           int," +
    "scc3TBSize_0xB173           int," +
    "scc4TBSize_0xB173           int," +
    "scc5TBSize_0xB173           int," +
    "scc6TBSize_0xB173           int," +
    "scc7TBSize_0xB173           int," +
    "totalTBSize_0xB173			int,"+
    "lteeNBId     int)"

  val qcomm2TableStruct:String = "(dmtimestamp             timestamp," +
    "index                   int," +
    "logcode                 string," +
    "hexlogcode              string," +
    "version                 int," +
    "wifissid                string," +
    "wifibssid               string," +
    "wifirssi                string," +
    "wifiipaddr              string," +
    "wifihiddenssid          string," +
    "wifinetworkid           string," +
    "wifimacaddr             string," +
    "wifilinkspeed           string," +
    "wifigateway             string," +
    "wifinetmask             string," +
    "wifiprimarydns          string," +
    "wifisecdns              string," +
    "wifidhcpserver          string," +
    "wifisupplicantstate     string," +
    "wificallstate           string," +
    "wifimodel               string," +
    "wifiisp                 string," +
    "wififrequency           string," +
    "wifichannel             string," +
    "wifidetailstate         string," +
    "inbldimgid              string," +
    "inbldx                  string," +
    "inbldy                  string," +
    "inbldusermark           string," +
    "inbldaccuracy           string," +
    "inbldaltitude           string," +
    "lteoos                  int," +
    "lterlf                  int," +
    "newcellcause            string," +
    "reselectionfailurecause string," +
    "lteintrareselfail       int," +
    "ltereselfromgsmumtsfail int," +
    "reselectionfromgsmumtsfailurecause      string," +
    "hofailurecause          string," +
    "hofailure               int," +
    "lteintrahofail          int," +
    "ltemobilityfromeutrafail        int," +
    "mobfromeutrafailurecause        string," +
    "ltesibreadfailure       int," +
    "receivedsibmask         int," +
    "radiolinkfailcause      string," +
    "emmstate                string," +
    "emmsubstate             string," +
    "mcc                     string," +
    "mnc                     string," +
    "mccdigit1               array<int>," +
    "mccdigit2               array<int>," +
    "mccdigit3               array<int>," +
    "mncdigit1               array<int>," +
    "mncdigit2               array<int>," +
    "mncdigit3               array<int>," +
    "stk_sid                 int," +
    "stk_nid                 int," +
    "stk_sys_mode            int," +
    "stkinfo_ecio            float," +
    "stk_ecio                int," +
    "stk_ecio_evdo           int," +
    "stk_srv_status          int," +
    "stk_gw_rscp             int," +
    "stk_rssi_wcdma          int," +
    "stk_sinr_evdo           int," +
    "stk_sinr                int," +
    "stk1_sid                int," +
    "stk1_nid                int," +
    "stk_sid0x184e           int," +
    "stk_nid0x184e           int," +
    "stk_sys_mode0_0x184e    int," +
    "stk_sys_mode1_0x184e    int," +
    "stkinfo_ecio0x184e      float," +
    "stk_ecio0x184e          float," +
    "stk_ecio_evdo0x184e     float," +
    "stk_srv_status0x184e    int," +
    "stk_gw_rscp0x184e       int," +
    "stk_rssi_wcdma0x184e    float," +
    "stk_sinr_evdo0x184e     int," +
    "stk_sinr0x184e          int," +
    "stk1_sid0x184e          int," +
    "stk1_nid0x184e          int," +
    "sys_id0x184e            int," +
    "stk_roam_status0x184e   int," +
    "sys_mode_operational_0x184e     int," +
    "stk1_sys_mode           int," +
    "stk1info_ecio           float," +
    "stk1_ecio_evdo          int," +
    "stk1_srv_status         int," +
    "stk1_gw_rscp            int," +
    "stk1_rssi_wcdma         int," +
    "hdrhybrid               int," +
    "stk1_sinr_evdo          int," +
    "stk_roam_status         int," +
    "stk1_roam_status        int," +
    "stk1_sinr               int," +
    "stk_rssi                float," +
    "stk1_rssi               float," +
    "bandclass               int," +
    "rlculdatapdubyte        array<bigint>," +
    "rlculctrlpdubytes       array<bigint>," +
    "macdlsfn                array<int>," +
    "macdlsubsfn             array<int>," +
    "macdlnumsamples         int," +
    "macdltbs                array<int>," +
    "maculsfn                array<int>," +
    "maculsubsfn             array<int>," +
    "maculnumsamples         int," +
    "maculgrant              array<int>," +
    "logrecorddescription    string," +
    "appversioncode          string," +
    "appversionname          string," +
    "basebandversion         string," +
    "deviceinfoversion       string," +
    "dmuser                  int," +
    "email                   string," +
    "firstname               string," +
    "lastname                string," +
    "iccid                   string," +
    "imei                    string," +
    "imsfeaturetag           string," +
    "imsstatus               string," +
    "imsi                    string," +
    "isinbuilding            string," +
    "islastchunk             string," +
    "mdn                     string," +
    "modelname               string," +
    "oemname                 string," +
    "osbuildid               string," +
    "ossdklevel              string," +
    "osversion               string," +
    "devicemodel             string," +
    "devicebuildversion      string," +
    "pdcpdlsubpacketversion  int," +
    "pdcpdldatabytes         array<bigint>," +
    "pdcpdlctrlbytes         array<bigint>," +
    "pdcpdlinvalidbytes      array<bigint>," +
    "pdcpulsubpacketversion  int," +
    "pdcpulctrlbytes         array<bigint>," +
    "pdcpuldatabytes         array<bigint>," +
    "pdcpulinvalidbytes      array<bigint>," +
    "pdcpdltput              bigint," +
    "pdcpultput              bigint," +
    "rlcdldatabytes          array<bigint>," +
    "rlcdlctrlbytes          array<int>," +
    "rlcdlinvalidbytes       array<bigint>," +
    "rlcdlnumrbs             int," +
    "txmodedl                int," +
    "txmodeul                int," +
    "exceptionoccured        boolean," +
    "exceptioncause          string," +
    "rlculnumrbs             int," +
    "pdcpdlnumrbs            int," +
    "pdcpulnumrbs            int," +
    "timingadvanceevt        int," +
    "lterrcstate             string," +
    "pdcpdltotalbytes        bigint," +
    "pdcpdltimestamp         bigint," +
    "pdcpultotalbytes        bigint," +
    "pdcpultimestamp         bigint," +
    "rlcdltotalbytes         bigint," +
    "rlcdltimestamp          bigint," +
    "rlcRbConfigIndex        array<int>," +
    "udid                    string," +
    "nr_rsrq                 float," +
    "nr_rsrp                 float," +
    "nr_rssnr                float," +
    "lte_rsrq                float," +
    "lte_rsrp                float," +
    "lte_rssnr               float," +
    "lte_enbId               int," +
    "cellId                  int," +
    "startTime               string," +
    "testName                string," +
    "resultType              string," +
    "avg_nr_rsrq             float," +
    "avg_nr_rsrp             float," +
    "avg_nr_rssnr            float," +
    "avg_lte_rsrq            float," +
    "avg_lte_rsrp            float," +
    "avg_lte_rssnr           float," +
    "task_time_median        float," +
    "task_time_05p           float," +
    "access_success          float," +
    "task_success            float," +
    "ttc_median              float," +
    "ttc_05p                 float," +
    "ttc_95p                 float," +
    "iteration_id            int," +
    "seq_id                  int," +
    "pingRtt                 int," +
    "downloadTput            float," +
    "uploadTput              float," +
    "rlcultotalbytes         bigint," +
    "rlcultimestamp          bigint," +
    "cdmaecio_0x184E         float," +
    "bandclass_0x184E        string," +
    "evdoecio_0x184E         float," +
    "evdocsinr_0x184E        int," +
    "wcdmarssi_0x184E        float," +
    "wcdmarscp_0x184E        int," +
    "wcdmaecio_0x184E        float," +
    "ltehandoversuccess      int," +
    "missingversion           int)"


  val b192TableStruct:String = "(dmtimestamp             timestamp," +
    "index                   int," +
    "logcode                 string," +
    "hexlogcode              string," +
    "version                 int," +
    "subpacketversion        int," +
    "earfcn_b192             array<int>," +
    "duplexingmode           array<string>," +
    "physicalcellid          array<int>," +
    "ftlcumulativefreqoffset array<int>," +
    "numberofsubpackets      int," +
    "instrsrprx_0            array<double>," +
    "instrsrprx_1            array<double>," +
    "instmeasuredrsrp        array<double>," +
    "instrsrqrx_0            array<double>," +
    "instrsrqrx_1            array<double>," +
    "instrsrq                array<double>," +
    "instrssirx_0            array<double>," +
    "instrssirx_1            array<double>," +
    "instrssi                array<double>," +
    "numofcell               array<int>," +
    "subpacketid             array<int>," +
    "exceptionoccured        boolean," +
    "exceptioncause          string," +
    "missingversion           int)"

  val b193TableStruct:String = "(dmtimestamp             timestamp," +
    "index                   int," +
    "logcode                 string," +
    "hexlogcode              string," +
    "version                 int," +
    "physicalcellid          array<int>," +
    "servingcellindex_b193   array<string>," +
    "isservingcell           array<int>," +
    "currentsfn              array<int>," +
    "currentsubframenumber   array<int>," +
    "isrestricted            array<int>," +
    "celltiming_0            array<int>," +
    "celltiming_1            array<int>," +
    "celltimingsfn_0         array<int>," +
    "celltimingsfn_1         array<int>," +
    "instrsrprx_0            array<double>," +
    "instrsrprx_1            array<double>," +
    "instrsrprx_2            array<double>," +
    "instrsrprx_3            array<double>," +
    "instmeasuredrsrp        array<double>," +
    "instrsrqrx_0            array<double>," +
    "instrsrqrx_1            array<double>," +
    "instrsrqrx_2            array<double>," +
    "instrsrqrx_3            array<double>," +
    "instrsrq                array<double>," +
    "instrssirx_0            array<double>," +
    "instrssirx_1            array<double>," +
    "instrssirx_2            array<double>," +
    "instrssirx_3            array<double>," +
    "instrssi                array<double>," +
    "residualfrequencyerror  array<int>," +
    "ftlsnrrx_0              array<double>," +
    "ftlsnrrx_1              array<double>," +
    "ftlsnrrx_2              array<double>," +
    "ftlsnrrx_3              array<double>," +
    "projectedsir            array<bigint>," +
    "posticrsrq              array<double>," +
    "cinr0                   array<int>," +
    "cinr1                   array<int>," +
    "cinr2                   array<int>," +
    "cinr3                   array<int>," +
    "numberofsubpackets      int," +
    "subpacketid             array<int>," +
    "subpacketsize           array<int>," +
    "earfcn_b193             array<int>," +
    "numofcell               array<int>," +
    "horxd_mode              array<int>," +
    "validrx                 array<string>," +
    "ftlcumulativefreqoffset array<int>," +
    "duplexingmode           array<string>," +
    "exceptionoccured        boolean," +
    "exceptioncause          string," +
    "missingversion           int)"

  val asnTableStruct:String = "(dmtimestamp             timestamp," +
    "index                   int," +
    "logcode                 string," +
    "hexlogcode              string," +
    "version                 int," +
    "exceptionoccured        boolean," +
    "exceptioncause          string," +
    "p0_nominalpucch         string," +
    "ssac_barringformmtel    boolean," +
    "upperlayerindication_r15    string," +
    "lterrcconrestrej        int," +
    "lterrcconrej            int," +
    "nrspcellpci             int," +
    "nrspcelldlfreq          int," +
    "nrspcellulfreq          int," +
    "nrspcellband            int," +
    "nrspcelldlbw            double," +
    "nrspcellulbw            double," +
    "nrspcellduplexmode      string," +
    "nrrrcreconfig           int," +
    "nrrbconfig              int," +
    "nrrrcreconfigcmp        int," +
    "lterrcconrel            int," +
    "lterrcconreq            int," +
    "lterrcconsetup          int," +
    "lterrcconsetupcmp       int," +
    "ltesecmodecmd           int," +
    "ltesecmodecmp           int," +
    "lterrcconreconfig       int," +
    "lterrcconreconfcmp      int," +
    "lteuecapenq             int," +
    "lteuecapinfo            int," +
    "ltehocmd                int," +
    "lteRrcConRestReq        int," +
    "lteRrcConRest           int," +
    "nrState                 string," +
    "NrRelease                int," +
    "MeasGapOffset            int," +
    "MeasGapRelease            int," +
    "nrFailureType           string," +
    "lterrcconrestcmp        int," +
    "missingversion           int)"

  val nasTableStruct:String = "(dmtimestamp             timestamp," +
    "index                   int," +
    "logcode                 string," +
    "hexlogcode              string," +
    "version                 int," +
    "qci                     string," +
    "pdnrejcause             string," +
    "pdnapnname              string," +
    "pdntype                 string," +
    "pdnreqtype              string," +
    "attrej                  string," +
    "authrej                 string," +
    "servicerej              string," +
    "tarej                   string," +
    "vopsstatus              string," +
    "attrejcause             string," +
    "servrejcause            string," +
    "emmtarejcause           string," +
    "emmauthrejcause         string," +
    "pdnrej                  string," +
    "imsi                    string," +
    "imei                    string," +
    "epsmobileidtype         string," +
    "contexttype             string," +
    "gutiiid                 string," +
    "attachtype              string," +
    "tatype                  string," +
    "taupdatetype            string," +
    "nas_msgtype             string," +
    "esmcause                string," +
    "linkedepsbearerid       string," +
    "ltepdnrej               int," +
    "lteattrej               int," +
    "lteauthrej              int," +
    "lteservicerej           int," +
    "ltetarej                int," +
    "exceptionoccured        boolean," +
    "exceptioncause          string," +
    "lteactdefcontacpt       int," +
    "lteactdedcontacpt       int," +
    "ltedeactcontacpt        int," +
    "lteesminfores           int," +
    "ltepdnconntreq          int," +
    "ltepdndisconreq         int," +
    "lteactdefbercontreq     int," +
    "lteactdedbercontreq     int," +
    "ltedeactbercontreq      int," +
    "lteesminforeq           int," +
    "lteattcmp               int," +
    "lteattreq               int," +
    "ltetareq                int," +
    "ltedetachreq            int," +
    "ltedetachacpt           int," +
    "ltesrvreq               int," +
    "lteattacpt              int," +
    "ltetaacpt               int," +
    "lteemminfo              int," +
    "lteEsmModifyEpsReq      int," +
    "lteEsmModifyEpsRej      int," +
    "lteEsmModifyEpsAccpt    int," +
    "lteActDefContRej        int," +
    "lteActDedContRej        int," +
    "dcnr                    string," +
    "n1Mode                  string," +
    "missingversion           int)"

  val ipTableStruct:String = "(dmtimestamp             timestamp," +
    "index                   int," +
    "logcode                 string," +
    "hexlogcode              string," +
    "version                 int," +
    "sipdirection            string," +
    "sipcseq                 string," +
    "sipmessagetype          string," +
    "sipbyereason            string," +
    "sipmsg                  string," +
    "voltedropevt            int," +
    "volteabortevt           int," +
    "voltetriggerevt         int," +
    "voltecallendevt         int," +
    "voLTECallNormalRelEvt   int," +
    "rtpdirection            string," +
    "rtpdlsn                 bigint," +
    "rtprxtimestamp          string," +
    "exceptionoccured        boolean," +
    "exceptioncause          string," +
    "missingversion           int)"

  val qcomm5GTableStruct:String = "(dmtimestamp             timestamp," +
    "index                   int," +
    "logcode                 string," +
    "hexlogcode              string," +
    "version                 int," +
    "exceptionoccured        boolean," +
    "exceptioncause          string," +
    "nrsbrsrp                array<string>," +
    "ccindex                 string," +
    "nrsbrsrq                array<string>," +
    "nrsbsnr                 string," +
    "NRServingRxBeamSNR0_0xB992  float," +
    "NRServingRxBeamSNR1_0xB992  float," +
    "nrbeamcount             string," +
    "nrsdlfrequency          string," +
    "nrsdlbandwidth          string," +
    "nrsphycellid            string," +
    "nrpci                   string," +
    "nrdlbler                array<string>," +
    "nrresidualbler          array<string>," +
    "nrdlmcs                 array<string>," +
    "nrdlmodtype             array<string>," +
    "numrb_0xb84d            string," +
    "NRSBRSRP_0xB97F         array<string>," +
    "CCIndex_0xB97F         array<int>," +
    "NRSBRSRQ_0xB97F         array<string>," +
    "NRBEAMCOUNT_0XB97F         array<int>," +
    "NRBandScc1_0xB97F          int," +
    "NrPCCARFCN_0XB97F          int," +
    "NrSCC1ARFCN_0XB97F         int," +
    "NRBandTypeSCC1_0xB97F      string," +
    "NRPCI_0XB97F         array<int>," +
    "NRServingBeamIndex_0xB97F           int," +
    "NRServingCellPci_0xB97F             array<int>," +
    "NRServingPCCPCI_0xB97F              array<int>," +
    "NRServingSCC1PCI_0xB97F             array<int>," +
    "NRServingSCC2PCI_0xB97F             array<int>," +
    "NRServingSCC3PCI_0xB97F             array<int>," +
    "NRServingSCC4PCI_0xB97F             array<int>," +
    "NRServingSCC5PCI_0xB97F             array<int>," +
    "NRServingPCCRxBeamId0_0xB97F        int," +
    "NRServingSCC1RxBeamId0_0xB97F       int," +
    "NRServingSCC2RxBeamId0_0xB97F       int," +
    "NRServingSCC3RxBeamId0_0xB97F       int," +
    "NRServingSCC4RxBeamId0_0xB97F       int," +
    "NRServingSCC5RxBeamId0_0xB97F       int," +
    "NRServingPCCRxBeamId1_0xB97F        int," +
    "NRServingSCC1RxBeamId1_0xB97F       int," +
    "NRServingSCC2RxBeamId1_0xB97F       int," +
    "NRServingSCC3RxBeamId1_0xB97F       int," +
    "NRServingSCC4RxBeamId1_0xB97F       int," +
    "NRServingSCC5RxBeamId1_0xB97F       int," +
    "NRServingPCCRxBeamRSRP0_0xB97F      array<float>," +
    "NRServingSCC1RxBeamRSRP0_0xB97F     array<float>," +
    "NRServingSCC2RxBeamRSRP0_0xB97F     array<float>," +
    "NRServingSCC3RxBeamRSRP0_0xB97F     array<float>," +
    "NRServingSCC4RxBeamRSRP0_0xB97F     array<float>," +
    "NRServingSCC5RxBeamRSRP0_0xB97F     array<float>," +
    "NRServingPCCRxBeamRSRP1_0xB97F      array<float>," +
    "NRServingSCC1RxBeamRSRP1_0xB97F     array<float>," +
    "NRServingSCC2RxBeamRSRP1_0xB97F     array<float>," +
    "NRServingSCC3RxBeamRSRP1_0xB97F     array<float>," +
    "NRServingSCC4RxBeamRSRP1_0xB97F     array<float>," +
    "NRServingSCC5RxBeamRSRP1_0xB97F     array<float>," +
    "NRServingPCCRSRP_0xB97F             array<float>," +
    "NRServingSCC1RSRP_0xB97F            array<float>," +
    "NRServingSCC2RSRP_0xB97F            array<float>," +
    "NRServingSCC3RSRP_0xB97F            array<float>," +
    "NRServingSCC4RSRP_0xB97F            array<float>," +
    "NRServingSCC5RSRP_0xB97F            array<float>," +
    "NRServingPCCRSRQ_0xB97F             array<float>," +
    "NRServingSCC1RSRQ_0xB97F            array<float>," +
    "NRServingSCC2RSRQ_0xB97F            array<float>," +
    "NRServingSCC3RSRQ_0xB97F            array<float>," +
    "NRServingSCC4RSRQ_0xB97F            array<float>," +
    "NRServingSCC5RSRQ_0xB97F            array<float>," +
    "NRRankIndexPCC                      int," +
    "NRRankIndexSCC1                     int," +
    "NRRankIndexSCC2                     int," +
    "NRRankIndexSCC3                     int," +
    "NRRankIndexSCC4                     int," +
    "NRRankIndexSCC5                     int," +
    "NRRankIndexSCC6                     int," +
    "NRRankIndexSCC7                     int," +
    "NRCQIWBPCC                          int," +
    "NRCQIWBSCC1                         int," +
    "NRCQIWBSCC2                         int," +
    "NRCQIWBSCC3                         int," +
    "NRCQIWBSCC4                         int," +
    "NRCQIWBSCC5                         int," +
    "NRCQIWBSCC6                         int," +
    "NRCQIWBSCC7                         int," +
    "isLogCode0xB97F         boolean," +
    "NRBandType_0xB97F       string," +
    "NRConnectivityType_0xB825  array<string>," +
    "NRConnectivityMode_0xB825  string," +
    "NRCellId_0xB825  string," +
    "NRArfcn_0xB825  string," +
    "NRBandInd_0xB97F        int," +
    "numinvalidpdus          array<string>," +
    "numduplicatepdu         array<string>," +
    "numdroppedpdu           array<string>," +
    "numrecords_0xb887       string," +
    "systemtime              array<string>," +
    "frame                   array<string>," +
    "numpdschstatus          array<string>," +
    "pdschstatusinfo         array<string>," +
    "carrierid_0xb887        array<string>," +
    "crcstatus_0xb887        array<string>," +
    "crcstate_0xb887         array<string>," +
    "tbsize_0xb887           array<string>," +
    "cellid_0xb887           array<string>," +
    "numrbs_0xb887           array<string>," +
    "numlayers_0xb887        array<string>," +
    "rntitype_0xb887         array<string>," +
    "txmode_0xb887           array<string>," +
    "NRMIMOType_0xB887       array<string>," +
    "crnti_0xb889            string," +
    "rachreason              string," +
    "carrierid_0xb889        string," +
    "rachcontention          string," +
    "nrpdschtput15khz          double," +
    "nrpdschtput30khz          double," +
    "nrpdschtput60khz          double," +
    "nrpdschtput120khz         double," +
    "nrpdschtput240khz         double," +
    "nrpdschtput               double," +
    "is5gtechnology            boolean," +
    "phychanbitmask_0xb884   array<string>," +
    "puschdlpathloss_0xb884   array<string>," +
    "pucchdlpathloss_0xb884  array<string>," +
    "srsdlpathloss_0xb884    array<string>," +
    "pracpathloss_0xb884     array<string>," +
    "puschtxpwr_0xb884       array<string>," +
    "tb_size_0xB888          bigint," +
    "tb_sizepcc_0xB888          bigint," +
    "tb_sizescc1_0xB888          bigint," +
    "tb_sizescc2_0xB888          bigint," +
    "tb_sizescc3_0xB888          bigint," +
    "tb_sizescc4_0xB888          bigint," +
    "tb_sizescc5_0xB888          bigint," +
    "tb_sizescc6_0xB888          bigint," +
    "tb_sizescc7_0xB888          bigint," +
    "pdschSum_0xB887         bigint," +
    "pdschSumPcc_0xB887      bigint," +
    "pdschSumScc1_0xB887     bigint," +
    "pdschSumScc2_0xB887     bigint," +
    "pdschSumScc3_0xB887     bigint," +
    "pdschSumScc4_0xB887     bigint," +
    "pdschSumScc5_0xB887     bigint," +
    "pdschSumScc6_0xB887     bigint," +
    "pdschSumScc7_0xB887     bigint," +
    "durationMs_0xB887       double," +
    "firstSfn_15kHz_0xB887      int," +
    "firstSfnSlot_15kHz_0xB887  int," +
    "lastSfn_15kHz_0xB887       int," +
    "lastSfnSlot_15kHz_0xB887   int," +
    "firstSfn_30kHz_0xB887      int," +
    "firstSfnSlot_30kHz_0xB887  int," +
    "lastSfn_30kHz_0xB887       int," +
    "lastSfnSlot_30kHz_0xB887   int," +
    "firstSfn_60kHz_0xB887      int," +
    "firstSfnSlot_60kHz_0xB887  int," +
    "lastSfn_60kHz_0xB887       int," +
    "lastSfnSlot_60kHz_0xB887   int," +
    "firstSfn_120kHz_0xB887     int," +
    "firstSfnSlot_120kHz_0xB887 int," +
    "lastSfn_120kHz_0xB887      int," +
    "lastSfnSlot_120kHz_0xB887  int," +
    "firstSfn_240kHz_0xB887     int," +
    "firstSfnSlot_240kHz_0xB887 int," +
    "lastSfn_240kHz_0xB887      int," +
    "lastSfnSlot_1240kHz_0xB887 int," +
    "missingversion           int,"+
    "NRServingBeamIndex       int)"

  val finalHiveTableStruct:String = "(dmtimestamp             timestamp," +
    "index                   int," +
    "logcode                 string," +
    "hexlogcode              string," +
    "version                 int," +
    "exceptionoccured        boolean," +
    "exceptioncause          string," +
    "missingversion          int," +
    "logrecordname           string," +
    "filteredrsrp            array<double>," +
    "numberofneighborcells   int," +
    "servingfilteredrsrp     double," +
    "dlgrantccid             array<array<array<int>>>," +
    "carrierindex0xb14d      string," +
    "carrierindex0xb14e      string," +
    "carrierindex0xb126      string," +
    "carrierindex            string," +
    "cqicw0                  int," +
    "cqicw1                  int," +
    "cqicw00xb14e            int," +
    "cqicw1show0xb14e        int," +
    "cqicw10xb14e            int," +
    "csftxmode               string," +
    "pucchreporttype         string," +
    "puschreportmode         string," +
    "rankindexstr            string," +
    "rankindexstr0xb14e      string," +
    "rankindexint            int," +
    "startsystemframenumber  int," +
    "startsystemsubframenumber       int," +
    "puschtxpower            array<int>," +
    "frequency               int," +
    "physicalcellid_qcomm    int," +
    "countLogcodeB126        int," +
    "numrecords0xb139        int," +
    "numrecords0xb172        int," +
    "numrecords0xb173        int," +
    "numrecords0xb16e        int," +
    "numrecords0xb16f        int," +
    "numrecords0xb18a        int," +
    "framenum                array<int>," +
    "subframenum             array<int>," +
    "crcresult               array<string>," +
    "discardedretxpresent    array<array<string>>," +
    "harqid                  array<array<int>>," +
    "ndi                     array<array<int>>," +
    "rv                      array<array<int>>," +
    "tb_index                array<array<int>>," +
    "tb_size0xb139           array<int>," +
    "tb_size0xb173           array<int>," +
    "numprb0xb173            array<int>," +
    "numlayers               array<int>," +
    "numtransportblockspresent       array<int>," +
    "servingcellindex        array<string>," +
    "numofstreams            array<bigint>," +
    "retransmissionnumber    array<array<string>>," +
    "transportblockcrc       array<array<string>>," +
    "format                  array<string>," +
    "rachproceduremode       string," +
    "rnti_type               string," +
    "rnti_value              int," +
    "pdcch_timing_sfn        array<int>," +
    "pdcch_timing_subsfn     array<int>," +
    "phich_value1            array<array<string>>," +
    "phich_value             array<array<string>>," +
    "modulationtype          array<string>," +
    "dlgrantpresent          array<string>," +
    "dlgrantformat           array<array<string>>," +
    "hopingflag              array<array<string>>," +
    "totaltxpower            array<array<bigint>>," +
    "chaintype               array<string>," +
    "fi                      array<int>," +
    "gi                      array<int>," +
    "pucch_tx_power0xb16e    array<int>," +
    "pucch_tx_power0xb16f    array<int>," +
    "insynccount             array<int>," +
    "outsyncbler             array<double>," +
    "outsynccount            array<int>," +
    "t310_timer_status       array<int>," +
    "cdrxevent               array<string>," +
    "currentsfnsf            array<int>," +
    "retxindex               array<string>," +
    "prb                     array<int>," +
    "modul                   array<string>," +
    "ulbandwidth             string," +
    "dlbandwidth             string," +
    "ltecellid               int," +
    "wcdmacellid             int," +
    "gsmcellid               int," +
    "allowedaccess           string," +
    "freqbandindicator       int," +
    "ulfreq                  int," +
    "dlfreq                  int," +
    "mcc_qcomm               int," +
    "mnc_qcomm               int," +
    "trackingareacode        int," +
    "modstream0              array<string>," +
    "modstream1              array<string>," +
    "pdschrntilid            int," +
    "pdschrntitype           array<string>," +
    "servingcellid           int," +
    "transmissionscheme      array<string>," +
    "freqselpmi              array<string>," +
    "spatialrank             array<string>," +
    "powerheadroom           array<bigint>," +
    "srstxpower              array<int>," +
    "pmiindex                int," +
    "ulcarrierindex          array<string>," +
    "bandclass_qcomm         int," +
    "channel0x1017           int," +
    "channel0x119a           int," +
    "pilotpn                 int," +
    "pilotpnaslist           array<int>," +
    "rxpower                 array<double>," +
    "txpower                 int," +
    "cdmatxstatus            string," +
    "hrpdstate               string," +
    "pdnrat                  string," +
    "lacid                   int," +
    "psc                     int," +
    "racid                   int," +
    "l2state                 string," +
    "rrstate                 string," +
    "rxlev                   int," +
    "bsicbcc                 int," +
    "bsicncc                 int," +
    "numtxantennas           array<string>," +
    "numrxantennas           array<string>," +
    "timingadvance           int," +
    "timingadvanceincl       string," +
    "dlpathloss0xb16e        array<int>," +
    "dlpathloss0xb16f        array<int>," +
    "lai                     array<tinyint>," +
    "bccharfcn               int," +
    "latitude                string," +
    "longitude               string," +
    "latitude2               string," +
    "longitude2              string," +
    "country                 string," +
    "county                  string," +
    "region                  string," +
    "statecode               string," +
    "evdorxpwr               array<double>," +
    "evdotxpwr               array<double>," +
    "vvqjitter               string," +
    "vvq                     string," +
    "rtploss                 string," +
    "cdmarftxpower           float," +
    "txgainadj               int," +
    "hasgps                  int," +
    "scc1cqicw0              int," +
    "scc2cqicw0              int," +
    "scc3cqicw0              int," +
    "scc4cqicw0              int," +
    "scc5cqicw0              int," +
    "scc1cqicw1              int," +
    "scc2cqicw1              int," +
    "scc3cqicw1              int," +
    "scc4cqicw1              int," +
    "scc5cqicw1              int," +
    "pccrankindex            int," +
    "scc1rankindex           int," +
    "scc2rankindex           int," +
    "scc3rankindex           int," +
    "scc4rankindex           int," +
    "scc5rankindex           int," +
    "firstfn_0xb173          int," +
    "lastfn_0xb173           int," +
    "firstsfn_0xb173         int," +
    "lastsfn_0xb173          int," +
    "pcelltbsize_0xb173      int," +
    "scc1tbsize_0xb173       int," +
    "scc2tbsize_0xb173       int," +
    "scc3tbsize_0xb173       int," +
    "scc4tbsize_0xb173       int," +
    "scc5tbsize_0xb173       int," +
    "scc6tbsize_0xb173       int," +
    "scc7tbsize_0xb173       int," +
    "totaltbsize_0xb173      int," +
    "distServingCellIndex_0xB173 int,"+
    "lteenbid                int," +
    "wifissid                string," +
    "wifibssid               string," +
    "wifirssi                string," +
    "wifiipaddr              string," +
    "wifihiddenssid          string," +
    "wifinetworkid           string," +
    "wifimacaddr             string," +
    "wifilinkspeed           string," +
    "wifigateway             string," +
    "wifinetmask             string," +
    "wifiprimarydns          string," +
    "wifisecdns              string," +
    "wifidhcpserver          string," +
    "wifisupplicantstate     string," +
    "wificallstate           string," +
    "wifimodel               string," +
    "wifiisp                 string," +
    "wififrequency           string," +
    "wifichannel             string," +
    "wifidetailstate         string," +
    "inbldimgid              string," +
    "inbldx                  string," +
    "inbldy                  string," +
    "inbldusermark           string," +
    "inbldaccuracy           string," +
    "inbldaltitude           string," +
    "lteoos                  int," +
    "lterlf                  int," +
    "newcellcause            string," +
    "reselectionfailurecause string," +
    "lteintrareselfail       int," +
    "ltereselfromgsmumtsfail int," +
    "reselectionfromgsmumtsfailurecause      string," +
    "hofailurecause          string," +
    "hofailure               int," +
    "lteintrahofail          int," +
    "ltemobilityfromeutrafail        int," +
    "mobfromeutrafailurecause        string," +
    "ltesibreadfailure       int," +
    "receivedsibmask         int," +
    "radiolinkfailcause      string," +
    "emmstate                string," +
    "emmsubstate             string," +
    "mcc_qcomm2              string," +
    "mnc_qcomm2              string," +
    "mccdigit1               array<int>," +
    "mccdigit2               array<int>," +
    "mccdigit3               array<int>," +
    "mncdigit1               array<int>," +
    "mncdigit2               array<int>," +
    "mncdigit3               array<int>," +
    "stk_sid                 int," +
    "stk_nid                 int," +
    "stk_sys_mode            int," +
    "stkinfo_ecio            float," +
    "stk_ecio                int," +
    "stk_ecio_evdo           int," +
    "stk_srv_status          int," +
    "stk_gw_rscp             int," +
    "stk_rssi_wcdma          int," +
    "stk_sinr_evdo           int," +
    "stk_sinr                int," +
    "stk1_sid                int," +
    "stk1_nid                int," +
    "stk_sid0x184e           int," +
    "stk_nid0x184e           int," +
    "stk_sys_mode0_0x184e    int," +
    "stk_sys_mode1_0x184e    int," +
    "stkinfo_ecio0x184e      float," +
    "stk_ecio0x184e          float," +
    "stk_ecio_evdo0x184e     float," +
    "stk_srv_status0x184e    int," +
    "stk_gw_rscp0x184e       int," +
    "stk_rssi_wcdma0x184e    float," +
    "stk_sinr_evdo0x184e     int," +
    "stk_sinr0x184e          int," +
    "stk1_sid0x184e          int," +
    "stk1_nid0x184e          int," +
    "sys_id0x184e            int," +
    "stk_roam_status0x184e   int," +
    "sys_mode_operational_0x184e     int," +
    "stk1_sys_mode           int," +
    "stk1info_ecio           float," +
    "stk1_ecio_evdo          int," +
    "stk1_srv_status         int," +
    "stk1_gw_rscp            int," +
    "stk1_rssi_wcdma         int," +
    "hdrhybrid               int," +
    "stk1_sinr_evdo          int," +
    "stk_roam_status         int," +
    "stk1_roam_status        int," +
    "stk1_sinr               int," +
    "stk_rssi                float," +
    "stk1_rssi               float," +
    "bandclass_qcomm2        int," +
    "rlculdatapdubyte        array<bigint>," +
    "rlculctrlpdubytes       array<bigint>," +
    "macdlsfn                array<int>," +
    "macdlsubsfn             array<int>," +
    "macdlnumsamples         int," +
    "macdltbs                array<int>," +
    "maculsfn                array<int>," +
    "maculsubsfn             array<int>," +
    "maculnumsamples         int," +
    "maculgrant              array<int>," +
    "logrecorddescription    string," +
    "appversioncode          string," +
    "appversionname          string," +
    "basebandversion         string," +
    "deviceinfoversion       string," +
    "dmuser                  int," +
    "email                   string," +
    "firstname               string," +
    "lastname                string," +
    "iccid                   string," +
    "imei_qcomm2             string," +
    "imsfeaturetag           string," +
    "imsstatus               string," +
    "imsi_qcomm2             string," +
    "isinbuilding            string," +
    "islastchunk             string," +
    "mdn                     string," +
    "modelname               string," +
    "oemname                 string," +
    "osbuildid               string," +
    "ossdklevel              string," +
    "osversion               string," +
    "devicemodel             string," +
    "devicebuildversion      string," +
    "pdcpdlsubpacketversion  int," +
    "pdcpdldatabytes         array<bigint>," +
    "pdcpdlctrlbytes         array<bigint>," +
    "pdcpdlinvalidbytes      array<bigint>," +
    "pdcpulsubpacketversion  int," +
    "pdcpulctrlbytes         array<bigint>," +
    "pdcpuldatabytes         array<bigint>," +
    "pdcpulinvalidbytes      array<bigint>," +
    "pdcpdltput              bigint," +
    "pdcpultput              bigint," +
    "rlcdldatabytes          array<bigint>," +
    "rlcdlctrlbytes          array<int>," +
    "rlcdlinvalidbytes       array<bigint>," +
    "rlcdlnumrbs             int," +
    "txmodedl                int," +
    "txmodeul                int," +
    "rlculnumrbs             int," +
    "pdcpdlnumrbs            int," +
    "pdcpulnumrbs            int," +
    "timingadvanceevt        int," +
    "lterrcstate             string," +
    "pdcpdltotalbytes        bigint," +
    "pdcpdltimestamp         bigint," +
    "pdcpultotalbytes        bigint," +
    "pdcpultimestamp         bigint," +
    "rlcdltotalbytes         bigint," +
    "rlcdltimestamp          bigint," +
    "rlcultotalbytes         bigint," +
    "rlcultimestamp          bigint," +
    "cdmaecio_0x184e         float," +
    "bandclass_0x184e        string," +
    "evdoecio_0x184e         float," +
    "evdosinr_0x184e         int," +
    "wcdmarssi_0x184e        float," +
    "wcdmarscp_0x184e        int," +
    "wcdmaecio_0x184e        float," +
    "ltehandoversuccess      int," +
    "status0x184e      boolean," +
    "subpacketversion_b192   int," +
    "earfcn_b192             array<int>," +
    "duplexingmode_b192      array<string>," +
    "physicalcellid_b192     array<int>," +
    "ftlcumulativefreqoffset_b192    array<int>," +
    "numberofsubpackets_b192 int," +
    "instrsrprx_0_b192       array<double>," +
    "instrsrprx_1_b192       array<double>," +
    "instmeasuredrsrp_b192   array<double>," +
    "instrsrqrx_0_b192       array<double>," +
    "instrsrqrx_1_b192       array<double>," +
    "instrsrq_b192           array<double>," +
    "instrssirx_0_b192       array<double>," +
    "instrssirx_1_b192       array<double>," +
    "instrssi_b192           array<double>," +
    "numofcell_b192          array<int>," +
    "subpacketid_b192        array<int>," +
    "physicalcellid_b193     array<int>," +
    "servingcellindex_b193   array<string>," +
    "isservingcell           array<int>," +
    "currentsfn              array<int>," +
    "currentsubframenumber   array<int>," +
    "isrestricted            array<int>," +
    "celltiming_0            array<int>," +
    "celltiming_1            array<int>," +
    "celltimingsfn_0         array<int>," +
    "celltimingsfn_1         array<int>," +
    "instrsrprx_0            array<double>," +
    "instrsrprx_1            array<double>," +
    "instrsrprx_2            array<double>," +
    "instrsrprx_3            array<double>," +
    "instmeasuredrsrp        array<double>," +
    "instrsrqrx_0            array<double>," +
    "instrsrqrx_1            array<double>," +
    "instrsrqrx_2            array<double>," +
    "instrsrqrx_3            array<double>," +
    "instrsrq                array<double>," +
    "instrssirx_0            array<double>," +
    "instrssirx_1            array<double>," +
    "instrssirx_2            array<double>," +
    "instrssirx_3            array<double>," +
    "instrssi                array<double>," +
    "residualfrequencyerror  array<int>," +
    "ftlsnrrx_0              array<double>," +
    "ftlsnrrx_1              array<double>," +
    "ftlsnrrx_2              array<double>," +
    "ftlsnrrx_3              array<double>," +
    "projectedsir            array<bigint>," +
    "posticrsrq              array<double>," +
    "cinr0                   array<int>," +
    "cinr1                   array<int>," +
    "cinr2                   array<int>," +
    "cinr3                   array<int>," +
    "numberofsubpackets      int," +
    "subpacketid             array<int>," +
    "subpacketsize           array<int>," +
    "earfcn_b193             array<int>," +
    "numofcell               array<int>," +
    "horxd_mode              array<int>," +
    "validrx                 array<string>," +
    "ftlcumulativefreqoffset array<int>," +
    "duplexingmode           array<string>," +
    "p0_nominalpucch         string," +
    "ssac_barringformmtel    boolean," +
    "upperlayerindication_r15    string," +
    "lterrcconrestrej        int," +
    "lterrcconrej            int," +
    "nrspcellpci             int," +
    "nrspcelldlfreq          int," +
    "nrspcellulfreq          int," +
    "nrspcellband            int," +
    "nrspcelldlbw            double," +
    "nrspcellulbw            double," +
    "nrspcellduplexmode      string," +
    "nrrrcreconfig           int," +
    "nrrbconfig              int," +
    "nrrrcreconfigcmp        int," +
    "lterrcconrel            int," +
    "lterrcconreq            int," +
    "lterrcconsetup          int," +
    "lterrcconsetupcmp       int," +
    "ltesecmodecmd           int," +
    "ltesecmodecmp           int," +
    "lterrcconreconfig       int," +
    "lterrcconreconfcmp      int," +
    "lteuecapenq             int," +
    "lteuecapinfo            int," +
    "ltehocmd                int," +
    "lterrcconrestreq        int," +
    "lterrcconrest           int," +
    "nrstate                 string," +
    "NrRelease                int," +
    "MeasGapOffset            int," +
    "MeasGapRelease            int," +
    "nrfailuretype           string," +
    "lterrcconrestcmp        int," +
    "status0xb0c0        boolean," +
    "nrrlf        int," +
    "subTitle        string," +
    "cellIdentity        string," +
    "cellIdentityHexDump        string," +
    "secondaryCellGroupCfg        int," +
    "asn4GPCI        int," +
    "asn5GPCI        int," +
    "nrScgCfgEvt        int," +
    "spCellBandDL        int," +
    "spCellNRARFCNDL        int," +
    "spCellSubCarSpaceDL        string," +
    "spCellNumPRBDL        int," +
    "spCellBandwidthDL        string," +
    "spCellDuplexMode        string," +
    "spCellTypeDL        string," +
    "spCellBandUL        int," +
    "spCellNRARFCNUL        int," +
    "spCellSubCarSpaceUL        string," +
    "spCellNumPRBUL        int," +
    "spCellBandwidthUL        string," +
    "spCellTypeUL        string," +
    "cdrxOndurationTimer        string," +
    "cdrxInactivityTimer        string," +
    "cdrxLongDrxCyle        string," +
    "cdrxShortDrxCyle        string," +
    "NRPrimaryPath           string," +
    "NRUlDataSplitThreshold  string," +
    "nrSRSTxSwitchConfig     string," +
    "qci                     string," +
    "pdnrejcause             string," +
    "pdnapnname              string," +
    "pdntype                 string," +
    "pdnreqtype              string," +
    "attrej                  string," +
    "authrej                 string," +
    "servicerej              string," +
    "tarej                   string," +
    "vopsstatus              string," +
    "attrejcause             string," +
    "servrejcause            string," +
    "emmtarejcause           string," +
    "emmauthrejcause         string," +
    "pdnrej                  string," +
    "imsi_nas                string," +
    "imei_nas                string," +
    "epsmobileidtype         string," +
    "contexttype             string," +
    "gutiiid                 string," +
    "attachtype              string," +
    "tatype                  string," +
    "taupdatetype            string," +
    "nas_msgtype             string," +
    "esmcause                string," +
    "linkedepsbearerid       string," +
    "ltepdnrej               int," +
    "lteattrej               int," +
    "lteauthrej              int," +
    "lteservicerej           int," +
    "ltetarej                int," +
    "lteactdefcontacpt       int," +
    "lteactdedcontacpt       int," +
    "ltedeactcontacpt        int," +
    "lteesminfores           int," +
    "ltepdnconntreq          int," +
    "ltepdndisconreq         int," +
    "lteactdefbercontreq     int," +
    "lteactdedbercontreq     int," +
    "ltedeactbercontreq      int," +
    "lteesminforeq           int," +
    "lteattcmp               int," +
    "lteattreq               int," +
    "ltetareq                int," +
    "ltedetachreq            int," +
    "ltedetachacpt           int," +
    "ltesrvreq               int," +
    "lteattacpt              int," +
    "ltetaacpt               int," +
    "lteemminfo              int," +
    "lteesmmodifyepsreq      int," +
    "lteesmmodifyepsrej      int," +
    "lteesmmodifyepsaccpt    int," +
    "lteactdefcontrej        int," +
    "lteactdedcontrej        int," +
    "dcnr                    string," +
    "n1mode                  string," +
    "sipdirection            string," +
    "sipcseq                 string," +
    "sipmessagetype          string," +
    "sipbyereason            string," +
    "sipmsg                  string," +
    "voltedropevt            int," +
    "volteabortevt           int," +
    "voltetriggerevt         int," +
    "voltecallendevt         int," +
    "voltecallnormalrelevt   int," +
    "rtpdirection            string," +
    "rtpdlsn                 bigint," +
    "rtprxtimestamp          string," +
    "statusvoltetriggerevt          boolean," +
    "statusrtpdlsn          boolean," +
    "statusvoltecallendevt          boolean," +
    "ipCallId          string," +
    "ipSubtitle          string," +
    "SSRCIDHex          string," +
    "ipType          string," +
    "rmMDN          string," +
    "cancelFromMDN          string," +
    "httpHost          string," +
    "httpMethod          string," +
    "httpContentLength          float," +
    "nrsbrsrp                array<string>," +
    "ccindex                 string," +
    "nrsbrsrq                array<string>," +
    "nrsbsnr                 string," +
    "nrsbsnr_0xb992          string," +
    "NRServingRxBeamSNR0_0xB992  float," +
    "NRServingRxBeamSNR1_0xB992  float," +
    "nrbeamcount             string," +
    "nrsdlfrequency          string," +
    "nrsdlbandwidth          string," +
    "nrsphycellid            string," +
    "nrpci                   string," +
    "nrdlbler                array<string>," +
    "nrresidualbler          array<string>," +
    "nrdlmcs                 array<string>," +
    "nrdlmodtype             array<string>," +
    "numrb_0xb84d            string," +
    "numReTxPDUSum_0xB84D       int," +
    "numMissedUMPDUSum_0xB84D   int," +
    "numDroppedPDUSum_0xB84D    int," +
    "numDataPDUSum_0xB84D       int," +
    "NRSBRSRP_0xB97F         array<string>," +
    "CCIndex_0xB97F          array<int>," +
    "NRSBRSRQ_0xB97F         array<string>," +
    "NRBEAMCOUNT_0XB97F      array<int>," +
    "NRBandScc1_0xB97F          int," +
    "NrPCCARFCN_0XB97F          int," +
    "NrSCC1ARFCN_0XB97F         int," +
    "NRBandTypeSCC1_0xB97F      string," +
    "NRPCI_0XB97F            array<int>," +
    "NRServingBeamIndex_0xB97F           int," +
    "NRServingCellPci_0xB97F             array<int>," +
    "NRServingPCCPCI_0xB97F              array<int>," +
    "NRServingSCC1PCI_0xB97F             array<int>," +
    "NRServingSCC2PCI_0xB97F             array<int>," +
    "NRServingSCC3PCI_0xB97F             array<int>," +
    "NRServingSCC4PCI_0xB97F             array<int>," +
    "NRServingSCC5PCI_0xB97F             array<int>," +
    "NRServingPCCRxBeamId0_0xB97F        int," +
    "NRServingSCC1RxBeamId0_0xB97F       int," +
    "NRServingSCC2RxBeamId0_0xB97F       int," +
    "NRServingSCC3RxBeamId0_0xB97F       int," +
    "NRServingSCC4RxBeamId0_0xB97F       int," +
    "NRServingSCC5RxBeamId0_0xB97F       int," +
    "NRServingPCCRxBeamId1_0xB97F        int," +
    "NRServingSCC1RxBeamId1_0xB97F       int," +
    "NRServingSCC2RxBeamId1_0xB97F       int," +
    "NRServingSCC3RxBeamId1_0xB97F       int," +
    "NRServingSCC4RxBeamId1_0xB97F       int," +
    "NRServingSCC5RxBeamId1_0xB97F       int," +
    "NRServingPCCRxBeamRSRP0_0xB97F      array<float>," +
    "NRServingSCC1RxBeamRSRP0_0xB97F     array<float>," +
    "NRServingSCC2RxBeamRSRP0_0xB97F     array<float>," +
    "NRServingSCC3RxBeamRSRP0_0xB97F     array<float>," +
    "NRServingSCC4RxBeamRSRP0_0xB97F     array<float>," +
    "NRServingSCC5RxBeamRSRP0_0xB97F     array<float>," +
    "NRServingPCCRxBeamRSRP1_0xB97F      array<float>," +
    "NRServingSCC1RxBeamRSRP1_0xB97F     array<float>," +
    "NRServingSCC2RxBeamRSRP1_0xB97F     array<float>," +
    "NRServingSCC3RxBeamRSRP1_0xB97F     array<float>," +
    "NRServingSCC4RxBeamRSRP1_0xB97F     array<float>," +
    "NRServingSCC5RxBeamRSRP1_0xB97F     array<float>," +
    "NRServingPCCRSRP_0xB97F             array<float>," +
    "NRServingSCC1RSRP_0xB97F            array<float>," +
    "NRServingSCC2RSRP_0xB97F            array<float>," +
    "NRServingSCC3RSRP_0xB97F            array<float>," +
    "NRServingSCC4RSRP_0xB97F            array<float>," +
    "NRServingSCC5RSRP_0xB97F            array<float>," +
    "NRServingPCCRSRQ_0xB97F             array<float>," +
    "NRServingSCC1RSRQ_0xB97F            array<float>," +
    "NRServingSCC2RSRQ_0xB97F            array<float>," +
    "NRServingSCC3RSRQ_0xB97F            array<float>," +
    "NRServingSCC4RSRQ_0xB97F            array<float>," +
    "NRServingSCC5RSRQ_0xB97F            array<float>," +
    "NRRankIndexPCC                      int," +
    "NRRankIndexSCC1                     int," +
    "NRRankIndexSCC2                     int," +
    "NRRankIndexSCC3                     int," +
    "NRRankIndexSCC4                     int," +
    "NRRankIndexSCC5                     int," +
    "NRRankIndexSCC6                     int," +
    "NRRankIndexSCC7                     int," +
    "NRCQIWBPCC                          int," +
    "NRCQIWBSCC1                         int," +
    "NRCQIWBSCC2                         int," +
    "NRCQIWBSCC3                         int," +
    "NRCQIWBSCC4                         int," +
    "NRCQIWBSCC5                         int," +
    "NRCQIWBSCC6                         int," +
    "NRCQIWBSCC7                         int," +
    "isLogCode0xB97F         boolean," +
    "NRBandType_0xB97F       string," +
    "NRConnectivityType_0xB825  array<string>," +
    "NRConnectivityMode_0xB825  array<string>," +
    "NRCellId_0xB825  string," +
    "NRArfcn_0xB825  string," +
    "NRBandInd_0xB97F       int," +
    "numinvalidpdus          array<string>," +
    "numduplicatepdu         array<string>," +
    "numdroppedpdu           array<string>," +
    "numrecords_0xb887       string," +
    "systemtime              array<string>," +
    "frame                   array<string>," +
    "numpdschstatus          array<string>," +
    "pdschstatusinfo         array<string>," +
    "carrierid_0xb887        array<string>," +
    "crcstatus_0xb887        array<string>," +
    "crcstate_0xb887         array<string>," +
    "tbsize_0xb887           array<string>," +
    "cellid_0xb887           array<string>," +
    "numrbs_0xb887           array<string>," +
    "numlayers_0xb887        array<string>," +
    "rntitype_0xb887         array<string>," +
    "txmode_0xb887           array<string>," +
    "NRMIMOType_0xB887       array<string>," +
    "NumReTx_0xB887           array<string>," +
    "NumReTx_cnt0_0xB887   int," +
    "NumReTx_cnt1_0xB887   int," +
    "NumReTx_cnt2_0xB887   int," +
    "NumReTx_cnt3_0xB887   int," +
    "NumReTx_cnt4_0xB887   int," +
    "CRCFail_cnt0_0xB887   int," +
    "CRCFail_cnt1_0xB887   int," +
    "CRCFail_cnt2_0xB887   int," +
    "CRCFail_cnt3_0xB887   int," +
    "CRCFail_cnt4_0xB887   int," +
    "crnti_0xb889            string," +
    "rachreason              string," +
    "carrierid_0xb889        string," +
    "rachcontention          string," +
    "nrpdschtput15khz        double," +
    "nrpdschtput30khz        double," +
    "nrpdschtput60khz        double," +
    "nrpdschtput120khz       double," +
    "nrpdschtput240khz       double," +
    "nrpdschtput             double," +
    "is5gtechnology          boolean," +
    "phychanbitmask_0xb884   array<string>," +
    "puschdlpathloss_0xb884  array<string>," +
    "pucchdlpathloss_0xb884  array<string>," +
    "srsdlpathloss_0xb884    array<string>," +
    "pracpathloss_0xb884     array<string>," +
    "puschtxpwr_0xb884       array<string>," +
    "puschdlpathloss_0xb8d2  string," +
    "pucchdlpathloss_0xb8d2  string," +
    "srsdlpathloss_0xb8d2    string," +
    "pracpathloss_0xb8d2     string," +
    "puschtxpwr_0xb8d2       string," +
    "NRSNR_0xB8D8            array<string>," +
    "NRSBSNR_0xB8DD          double," +
    "NRSBSNRRx0_0xB8DD       double," +
    "NRSBSNRRx1_0xB8DD       double," +
    "NRSBSNRRx2_0xB8DD       double," +
    "NRSBSNRRx3_0xB8DD       double," +
    "tb_size_0xb888          bigint," +
    "pdschsum_0xb887         bigint," +
    "pdschsumpcc_0xb887      bigint," +
    "pdschsumscc1_0xb887     bigint," +
    "pdschsumscc2_0xb887     bigint," +
    "pdschsumscc3_0xb887     bigint," +
    "pdschsumscc4_0xb887     bigint," +
    "pdschsumscc5_0xb887     bigint," +
    "pdschsumscc6_0xb887     bigint," +
    "pdschsumscc7_0xb887     bigint," +
    "durationms_0xb887       double," +
    "firstsfn_15khz_0xb887   int," +
    "firstsfnslot_15khz_0xb887       int," +
    "lastsfn_15khz_0xb887    int," +
    "lastsfnslot_15khz_0xb887        int," +
    "firstsfn_30khz_0xb887   int," +
    "firstsfnslot_30khz_0xb887       int," +
    "lastsfn_30khz_0xb887    int," +
    "lastsfnslot_30khz_0xb887        int," +
    "firstsfn_60khz_0xb887   int," +
    "firstsfnslot_60khz_0xb887       int," +
    "lastsfn_60khz_0xb887    int," +
    "lastsfnslot_60khz_0xb887        int," +
    "firstsfn_120khz_0xb887  int," +
    "firstsfnslot_120khz_0xb887      int," +
    "lastsfn_120khz_0xb887   int," +
    "lastsfnslot_120khz_0xb887       int," +
    "firstsfn_240khz_0xb887  int," +
    "firstsfnslot_240khz_0xb887      int," +
    "lastsfn_240khz_0xb887   int," +
    "lastsfnslot_240khz_0xb887       int," +
    "nrservingbeamindex       int," +
    "status0xb888       boolean," +
    "status0xb887       boolean," +
    "numerology_0xB887  array<string>," +
    "NRTxBeamIndexPCC   array<int>," +
    "NRTxBeamIndexSCC1  array<int>," +
    "rsrp1_0xB891       string," +
    "rachResult_0xb88a  string," +
    "rachAttempted_0xb88a     boolean,"+
    "resource1_0xB891     string,"+
    "rachTriggered_0xb889     boolean,"+
    "RachFailure_0xb88a int," +
    "txNewTbSum_0xB883 int,"+
    "txReTbSum_0xB883 int,"+
    "tbNewTxBytesB881 int,"+
    "numNewTxTbB881 int,"+
    "numReTxTbB881 int,"+
    "nr5GPhyULInstTputPCC_0XB883 double,"+
    "nr5GPhyULInstTputSCC1_0XB883 double,"+
    "nr5GPhyULInstTput_0XB883 double,"+
    "nr5GPhyULInstRetransRatePCC_0XB883 double,"+
    "nr5GPhyULInstRetransRateSCC1_0XB883 double,"+
    "nr5GPhyULInstRetransRate_0XB883 double,"+
    "txTotalSum_0xB883 int,"+
    "numerology_0xB883 array<string>,"+
    "carrierId_0XB883 array<int>,"+
    "harq_0XB883 array<int>,"+
    "mcs_0XB883 array<int>,"+
    "numrbs_0XB883 array<int>,"+
    "tbsize_0XB883 array<long>,"+
    "txmode_0XB883 array<string>,"+
    "txtype_0XB883 array<int>,"+
    "bwpidx_0XB883 array<int>,"+
    "numNEW_TX_0XB883     int," +
    "numRE_TX_0XB883      int," +
    "numNEW_TXPCC_0XB883  int," +
    "numNEW_TXSCC1_0XB883 int," +
    "numRE_TXPCC_0XB883   int," +
    "numRE_TXSCC1_0XB883  int," +
    "numRE_TXRV_0_0XB883  int," +
    "numRE_TXRV_1_0XB883  int," +
    "numRE_TXRV_2_0XB883  int," +
    "numRE_TXRV_3_0XB883  int," +
    "NRPUSCHWaveformPCC   String," +
    "NRPUSCHWaveformSCC1  String," +
    "totalTxBytes_0xB868 int,"+
    "totalReTxPDUsSum_0x0xB868 int," +
    "totalTxPDUsSum_0x0xB868 int," +
    "totalNumRxBytes_0xB860 int,"+
    "totalNumDiscardPacketsSum_0xB860 int," +
    "numRXPacketsSum_0xB860 int," +
    "cdrxKpi0xB890List array<struct<slot_0xB890:array<string>,frame_0xB890:array<string>,cdrxEvent_0xB890:array<string>,prevState_0xB890:array<string>>>,"+
    "slot0xB890 array<string>,"+
    "sfn0xB890 array<string>,"+
    "numerology0xB890 array<string>,"+
    "rlcDataBytesVal_0xB84D int,"+
    "dataPDUBytesReceivedAllRBSum_0xB842    int," +
    "controlPDUBytesReceivedAllRBSum_0xB842  int,"+
    "numMissPDUToUpperLayerSum_0xB842   int," +
    "numDataPDUReceivedSum_0xB842       int," +
    "NRBeamFailureEvt    int," +
    "NRRrcNewCellIndEvt    int," +
    "NRRrcHoFailEvt    int," +
    "NRRrcHoFailEvtCause    string," +
    "NRRlfEvt    int," +
    "NRRlfEvtCause    string," +
    "NRScgFailureEvt    int," +
    "NRScgFailureEvtCause    string,"+
    "BFDIND    boolean,"+
    "frequency_SIG		string,"+
    "channelNumber_SIG		string,"+
    "bandwidth_SIG		string,"+
    "numSignals_SIG		string,"+
    "cellId_SIG		array<string>,"+
    "RefPower_SIG		array<string>,"+
    "RefQuality_SIG		array<string>,"+
    "CINR_SIG		array<string>," +
    "bandwidth0x2406_SIG String,"+
    "frequency0x2406_SIG  String," +
    "channelNumber0x2406_SIG String," +
    "power0x2406_SIG String," +
    "numSignals0x2406_SIG String," +
    "cellId0x2406_SIG array<string>," +
    "SecondarySyncQuality0x2406_SIG array<string>," +
    "SecondarySyncPower0x2406_SIG array<string>," +
    "CINR0x2406_SIG array<string>," +
    "PrimarySyncQuality0x2406_SIG array<string>," +
    "PrimarySyncPower0x2406_SIG array<string>," +
    "cpType0x2406_SIG array<string>," +
    "frequency0x2408_SIG string," +
    "bandwidth0x2408_SIG string," +
    "numSignals0x2408_SIG string," +
    "CINR0x2408_SIG array<string>," +
    "cellId0x2408_SIG array<string>," +
    "totalRsPower0x2408_SIG array<string>," +
    "overallPower0x2408_SIG array<string>," +
    "overallQuality0x2408_SIG array<string>," +
    "cpType0x2408_SIG array<string>," +
    "antQuality0x2408_SIG array<string>," +
    "antPower0x2408_SIG array<string>," +
    "carrierRSSI0x2408_SIG string," +
    "numberOfTxAntennaPorts0x2408_SIG array<string>," +
    "frequency0x240D_SIG	string," +
    "channelNumber0x240D_SIG	string," +
    "bandwidth0x240D_SIG	string," +
    "numSignals0x240D_SIG	string," +
    "carrierRSSI0x240D_SIG string," +
    "PCI0x240D_SIG	array<string>," +
    "RSRP0x240D_SIG	array<string>," +
    "RSRQ0x240D_SIG	array<string>," +
    "CINR0x240D_SIG	array<string>," +
    "numberOfTxAntennaPorts0x240D_SIG	array<string>," +
    "channelNumber0x2501_SIG	 string," +
    "operatingBand0x2501_SIG	 string," +
    "ssbRSSI0x2501_SIG	 string," +
    "numSSBurstDataBlocks0x2501_SIG	 string," +
    "PCI0x2501_SIG	array<string>," +
    "frequency0x2501_SIG	array<string>," +
    "subCarrierSpacing0x2501_SIG	array<string>," +
    "numBeams0x2501_SIG	array<string>," +
    "beamIndex0x2501_SIG	array<string>," +
    "pssBRSRP0x2501_SIG	array<string>," +
    "pssBRSRQ0x2501_SIG	array<string>," +
    "pssCINR0x2501_SIG	array<string>," +
    "sssBRSRP0x2501_SIG	array<string>," +
    "sssBRSRQ0x2501_SIG	array<string>," +
    "sssCINR0x2501_SIG	array<string>," +
    "sssDelay0x2501_SIG	array<string>," +
    "ssbBRSRP0x2501_SIG	array<string>," +
    "ssbBRSRQ0x2501_SIG	array<string>," +
    "ssbCINR0x2501_SIG	array<string>," +
    "RMTestName      string," +
    "RMTestState   string," +
    "TestCycleId   string," +
    "DeviceTime   string," +
    "DeviceId  string," +
    "M2MReceiveStart  string," +
    "M2MReceiveEnd  string," +
    "M2MCallStart  string," +
    "M2MCallEnd  string," +
    "TRANSMITStart  string," +
    "TRANSMITEnd  string," +
    "UDPECHOStart  string," +
    "UDPECHOEnd  string," +
    "SMSStart  string," +
    "SMSEnd  string," +
    "IdleStart  string," +
    "IdleEnd    string," +
    "DNSStart   string," +
    "DNSEnd    string," +
    "LDRStart   string," +
    "LDREnd    string," +
    "LDRSStart   string," +
    "LDRSEnd    string," +
    "UPLOADStart   string," +
    "UPLOADEnd    string," +
    "DOWNLOADStart   string," +
    "DOWNLOADEnd    string," +
    "frequencyRSRP0x2157_SIG array<struct<freq:int,rsrp:double>>,"+
    "freqKpiList0x2406 array<struct<freq:int,channelNumber:string,cinr:array<string>,cellId:array<string>,primaryRsrp:array<string>,primaryRsrq:array<string>,secondaryRsrp:array<string>,secondaryRsrq:array<string>,cptType:array<string>>>," +
    "freqKpiList0x240b array<struct<freq:int,ChannelNumber:int, Bandwidth:string, cinr:array<string>,cellId:array<string>,primaryRsrp:array<string>,primaryRsrq:array<string>>>," +
    "pciKpi0x240C_SIG array<struct<centerFreq:int,numSignals:int, pci:array<string>, rsrp:array<string>,rsrq:array<string>,rscinr:array<string>,numberOfAntennas:array<string>,antennaRsrp:array<string>,antennaRsrq:array<string>,antennaCinr:array<string>>>," +
    "lteTopNSignalkpiList array<struct<freq:int,ChannelNumber:int, Bandwidth:string, cinr:array<string>, cellId:array<string>, primaryRsrp:array<string>, primaryRsrq:array<string>>>," +
    "nrTopNSignalKpiList array<struct<signalNumber:int, freq:int, channelNumber:int, numCells:int, ssbRssi:double, band:string, subCarrierSpacing:int, " +
    "pssCinr:array<string>, pssRsrp:array<string>, pssRsrq:array<string>, sssCinr:array<string>, sssRsrp:array<string>, sssRsrq:array<string>, " +
    "ssbCinr:array<string>, ssbRsrp:array<string>, ssbRsrq:array<string>, cellId:array<string>, beamIndex:array<string>>>," +
    "lteBlindScanKpiList array<struct<freq:int,ChannelNumber:int, Bandwidth:string, cinr:array<string>, cellId:array<string>, primaryRsrp:array<string>, primaryRsrq:array<string>>>," +
    "nrBlindScanKpiList array<struct<freq:int,ChannelNumber:int, Bandwidth:string, cinr:array<string>, cellId:array<string>, primaryRsrp:array<string>, primaryRsrq:array<string>>>" +
    ")"


  def generateHiveSchema(recordType:String, dbName:String, tableName:String, hdfsPath:String)={
    "create external table "+ dbName + tableName + getColumnSchema(recordType)+" partitioned by (fileName string, insertedDate string, testId string) stored as parquet LOCATION '"+hdfsPath+"/apps/hive/warehouse/dmat_logs.db/"+tableName+"'"
  }

  def alterhivetable(dbName:String, tableName:String,fileName: String,insertedDate: String,testId: String,hdfsPath:String,dateTime: Long) : String={
    "alter table "+dbName + tableName  + s" add partition(fileName='${fileName}',insertedDate='${insertedDate}',testId='${testId}') location '"+hdfsPath+"/apps/hive/warehouse/dmat_logs.db/"+tableName+"/"+dateTime+s"/fileName=${fileName}/insertedDate=${insertedDate}/testId=${testId}'"
  }
  def deleteHivePartitionIfExists(spark:SparkSession,fileName:String,hiveTblName:String)={
    if(spark.catalog.tableExists("dmat_logs.finallogrecord_dmat"+hiveTblName)){
      spark.sql("ALTER TABLE dmat_logs.finallogrecord_dmat" + hiveTblName + " DROP IF EXISTS PARTITION (fileName='" + fileName + "')")
    }
  }
  def getColumnSchema(recordType:String)={
    recordType.toUpperCase match {
      case "QCOMM" =>
        qcommTableStruct
      case "QCOMM2" =>
        qcomm2TableStruct
      case "B192" =>
        b192TableStruct
      case "B193" =>
        b193TableStruct
      case "ASN" =>
        asnTableStruct
      case "NAS" =>
        nasTableStruct
      case "IP" =>
        ipTableStruct
      case "QCOMM5G" =>
        qcomm5GTableStruct
      case "HIVE" =>
        finalHiveTableStruct
    }

  }
}
