package com.verizon.oneparser.schema

import java.sql.Timestamp

case class LogRecord_NAS(fileName: String,
                         dmTimeStamp: Timestamp,
                         index: Int,
                         logCode: String,
                         hexLogCode: String,
                         version: Int,
                         insertedDate:String = null,
                         testId: Int,
                         qci:String = null,
                         pdnRejCause:String = null,
                         pdnApnName:String = null,
                         pdnType:String = null,
                         pdnReqType:String = null,
                         attRej:String = null,
                         authRej:String = null,
                         serviceRej:String = null,
                         taRej:String = null,
                         voPSStatus:String = null,
                         attRejCause:String = null,
                         servRejCause:String = null,
                         emmTaRejCause:String = null,
                         emmAuthRejCause:String = null,
                         pdnRej:String = null,
                         imsi:String=null,
                         imei:String = null,
                         epsMobileIdType:String = null,
                         contextType:String = null,
                         gutiIId:String = null,
                         attachType:String = null,
                         taType:String=null,
                         taUpdateType:String = null,
                         NAS_MsgType:String =null,
                         esmCause:String = null,
                         linkedEpsBearerId:String = null,
                         ltePdnRej:Integer = null,
                         lteAttRej:Integer = null,
                         lteAuthRej:Integer = null,
                         lteServiceRej:Integer = null,
                         lteTaRej:Integer = null,
                         exceptionOccured:Boolean = false,
                         exceptionCause:String=null,
                         lteActDefContAcpt :Integer = null,
                         lteActDedContAcpt :Integer = null,
                         lteDeactContAcpt :Integer = null,
                         lteEsmInfoRes :Integer = null,
                         ltePdnConntReq :Integer = null,
                         ltePdnDisconReq :Integer = null,
                         lteActDefBerContReq :Integer = null,
                         lteActDedBerContReq :Integer = null,
                         lteDeactBerContReq :Integer = null,
                         lteEsmInfoReq :Integer = null,
                         lteAttCmp :Integer = null,
                         lteAttReq :Integer = null,
                         lteTaReq :Integer = null,
                         lteDetachReq :Integer = null,
                         lteDetachAcpt :Integer = null,
                         lteSrvReq :Integer = null,
                         lteAttAcpt :Integer = null,
                         lteTaAcpt :Integer = null,
                         lteEmmInfo :Integer = null,
                         lteEsmModifyEpsReq :Integer = null,
                         lteEsmModifyEpsRej :Integer = null,
                         lteEsmModifyEpsAccpt :Integer = null,
                         lteActDefContRej :Integer = null,
                         lteActDedContRej :Integer = null,
                         dcnr:String = null,
                         n1Mode:String = null,
                         missingVersion:Int = -1
                        )