package com.verizon.oneparser.schema

import java.sql.Timestamp

case class LogRecord_ASN(fileName: String,
                         dmTimeStamp: Timestamp,
                         index: Int,
                         logCode: String,
                         hexLogCode: String,
                         version: Int,
                         insertedDate:String = "",
                         testId: Int,
                         exceptionOccured:Boolean = false,
                         exceptionCause:String="",
                         p0_NominalPUCCH:String="",
                         ssac_BarringForMMTEL:Boolean=false,
                         upperLayerIndication_r15:String = null,
                         lteRrcConRestRej:Integer = null,
                         lteRrcConRej:Integer = null,
                         nrSpcellPci:Integer = null,
                         nrSpcellDlFreq:Integer = null,
                         nrSpcellUlFreq:Integer = null,
                         nrSpcellBand:Integer = null,
                         nrSpcellDlBw:java.lang.Double = null,
                         nrSpcellUlBw:java.lang.Double = null,
                         nrSpcellDuplexMode:String = null,
                         nrRrcReConfig: Integer = null,
                         nrRbConfig: Integer = null,
                         nrRrcReConfigCmp: Integer = null,
                         lteRrcConRel :Integer = null,
                         lteRrcConReq :Integer = null,
                         lteRrcConSetup :Integer = null,
                         lteRrcConSetupCmp :Integer = null,
                         lteSecModeCmd :Integer = null,
                         lteSecModeCmp :Integer = null,
                         lteRrcConReconfig :Integer = null,
                         lteRrcConReconfCmp :Integer = null,
                         lteUeCapEnq :Integer = null,
                         lteUeCapInfo :Integer = null,
                         lteHoCmd :Integer = null,
                         lteRrcConRestReq:Integer = null,
                         lteRrcConRest:Integer = null,
                         nrState:String=null,
                         nrFailureType:String=null,
                         lteRrcConRestCmp:Integer = null,
                         missingVersion:Int = -1,
                         NrRelease:Integer = null,
                         MeasGapOffset:Integer = null,
                         MeasGapRelease:Integer = null
)
